### ISSUE TITLE
[KT-9] Добавить валидацию на рег/авт

### ISSUE THREAD

**Issue by CNNOM** [CNNOM/KT#11]

**Comment by a-chernousov** [comment]
регистрация complite

**Comment by a-chernousov** [comment]
авторизация complite

**Comment by a-chernousov** [comment]
добавление списка лёгких паролей и основных существующий доменов почты

**Comment by a-chernousov** [comment]
так же в этой ветки сделана задача [KT-10] Добавить хеширование пароля

**Comment by a-chernousov** [comment]
**Предложение: сделать капчу при регистрации пользователя** @CNNOM
