### ISSUE TITLE
[KT-2] Создание Логотипа

### ISSUE THREAD

**Issue by CNNOM** [CNNOM/KT#2]
Создать логотип "Kiber Two", стиль - минимализм

**Comment by a-chernousov** [comment]
hddtfygufh

**Comment by a-chernousov** [comment]
ЛЁХА НУБИК

**Comment by stasia27** [comment]
![лого](https://github.com/user-attachments/assets/21b0b6df-3cf9-4e10-898e-4afd9c35b507)
![доп варики](https://github.com/user-attachments/assets/3a8ed978-95b7-4953-b02e-5906f4059dbf)
